#.github/workflows/linting.yaml
name: Linting Checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**' # Every branch

env:
  USER: "github_runner"
  HOME: "/tmp"

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #           check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Set PATH
        run: |
          echo "/tmp/micromamba/envs/surfExp/bin" >> $GITHUB_PATH

      - name: Set python
        run: |
          poetry env use /tmp/micromamba/envs/surfExp/bin/python

      #- name: Load cached venv (if cache exists)
      #  id: cached-poetry-dependencies
      #  uses: actions/cache@v4
      #  with:
      #    path: .venv
      #    key: venv-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies (if venv cache is not found)
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction --no-root --only linting

      - name: Install the project itself
        run: |
          poetry install --no-interaction --only-root

      #----------------------------------------------
      #         Run the linting checks
      #----------------------------------------------
      - name: Linting
        run: |
          poetry run poetry devtools lint
